services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5434:5432"
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: taskmanager
    volumes:
      - pg_data:/bitnami/postgresql

volumes:
  pg_data:
